### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by agius** [agius/secret-shield-refactor-draft#1]
Steps to get to feature parity w/ secret-shield:

- [X] reproduce all rules & config settings as plugins
- [X] scan string
- [X] scan file
- [X] scan directory
- [X] clone remote repo & scan
- [X] scan git diff
- [ ] [CloudFormation templates](https://github.com/mapbox/secret-shield/blob/92b431e0252d40ad54a10860d1fb14de082c5c55/searchCFTemplate.js)? not sure secret-shield really needs to do this
- [ ] git integrations
  - [ ] pre-commit hook
  - [ ] husky integration
- [ ] enabled repos
  - [ ] check for global install
  - [ ] check for updated to latest vesion
  - [ ] [grace-period checker](https://github.com/mapbox/secret-shield/blob/master/docs/enabledRepositories.md#what-is-the-grace-period)
- [ ] watchbot job (unless... should maybe be a separate repo? watchbot shouldn't need to be Node 4.3 compat)

Planned:

- [ ] configuration
  - [ ] `.shieldrc.js` and/or `.shieldrc.json` ? in-repo or global, eslint-style
  - [ ] `secretShieldConfig` in `package.json`
- [ ] `gitignore-filter` plugin to skip files that are `.gitignore` 'd when scanning repos
- [ ] formatter plugins for formatting output ( [logfmt](https://brandur.org/logfmt), json, etc )
- [ ] reporter plugins for outputting logs to destinations ( stdout / stderr, elasticsearch, rsyslog destinations, etc)
